CREATE GLOBAL TEMPORARY TABLE  UDO_SPORT
   (	INN VARCHAR2(50) DEFAULT NULL,
    SPORTNUMBER  VARCHAR2(50) DEFAULT NULL,
    CALPLAN VARCHAR2(50) DEFAULT NULL,
    SPORTNAME VARCHAR2(4000) DEFAULT NULL,
    SERV VARCHAR2(4000) DEFAULT NULL,
    SPORTYPE VARCHAR2(4000) DEFAULT NULL,
    PLACE VARCHAR2(4000) DEFAULT NULL,
    STARTDATE VARCHAR2(4000) DEFAULT NULL,
    FINDATE VARCHAR2(4000) DEFAULT NULL,
	IDENT VARCHAR2(4000) DEFAULT NULL
   ) ON COMMIT PRESERVE ROWS


create or replace procedure UDO_P_SPORT()
begin
    null;
end;
