CREATE  TABLE  XML_EXP1
   (
    VERSION VARCHAR2(4000) DEFAULT NULL,       -- версия
    INN VARCHAR2(4000) DEFAULT NULL,           -- ИНН
	FOTYPE2 VARCHAR2(4000) DEFAULT NULL,       -- Вид финансового обеспечения
	CODE VARCHAR2(4000) DEFAULT NULL,          -- Коды разделов и подразделов классификации расходов бюджетов ?
	PRECODE VARCHAR2(4000) DEFAULT NULL,       -- Коды подразделов классификации расходов бюджетов
	PARTCODE VARCHAR2(4000) DEFAULT NULL,      -- Целевая статья
	KVR VARCHAR2(4000) DEFAULT NULL,           -- KVR
	KOSGU VARCHAR2(4000) DEFAULT NULL,         -- KOSGU
	SUMM1 VARCHAR2(4000) DEFAULT NULL,         -- сумма за 1 квартал
	SUMM2 VARCHAR2(4000) DEFAULT NULL,         -- сумма за 2 квартал
	SUMM3 VARCHAR2(4000) DEFAULT NULL,         -- сумма за 3 квартал
	SUMM4 VARCHAR2(4000) DEFAULT NULL,         -- сумма за 4 квартал
	IDENT number DEFAULT NULL
   )
CREATE  TABLE  XML_EXP2
    (
        CREATEDATE         VARCHAR2(4000) DEFAULT NULL,
        POSITION           VARCHAR2(4000) DEFAULT NULL,
        FINANCIALYEAR      VARCHAR2(4000) DEFAULT NULL,
        FULLNAME           VARCHAR2(4000) DEFAULT NULL,
        INN                VARCHAR2(4000) DEFAULT NULL,
        FIRSTYEAR          VARCHAR2(4000) DEFAULT NULL,
        LASTYEAR           VARCHAR2(4000) DEFAULT NULL,
        LAW                VARCHAR2(4000) DEFAULT NULL,
        CONTENT            VARCHAR2(4000) DEFAULT NULL,
        SUPPLIER           VARCHAR2(4000) DEFAULT NULL,
        INNSUPPLIER        VARCHAR2(4000) DEFAULT NULL,
        CONTRACTNUMBER     VARCHAR2(4000) DEFAULT NULL,
        CONCLUSIONDATE     VARCHAR2(4000) DEFAULT NULL,
        EXPIRATIONDATE     VARCHAR2(4000) DEFAULT NULL,
        REESTRNUMBER       VARCHAR2(4000) DEFAULT NULL,
        SCHEDULENUMBER     VARCHAR2(4000) DEFAULT NULL,
        PUBLICATIONDATE    VARCHAR2(4000) DEFAULT NULL,
        IDENTIFICATIONCODE VARCHAR2(4000) DEFAULT NULL,
        METHODSUPPLIER     VARCHAR2(4000) DEFAULT NULL,
        KOSGU              VARCHAR2(4000) DEFAULT NULL,
        KVR                VARCHAR2(4000) DEFAULT NULL,
        TYPEFO             VARCHAR2(4000) DEFAULT NULL,
        SECTIONSUBSECTION  VARCHAR2(4000) DEFAULT NULL,
        CSR                VARCHAR2(4000) DEFAULT NULL,
        KBKKVR             VARCHAR2(4000) DEFAULT NULL,
        TYPEBS             VARCHAR2(4000) DEFAULT NULL,
        OBJECTS            VARCHAR2(4000) DEFAULT NULL,
        FINNUMBER          VARCHAR2(4000) DEFAULT NULL,
        FINPRICE           VARCHAR2(4000) DEFAULT NULL,
        FIRSTNUMBER        VARCHAR2(4000) DEFAULT NULL,
        FIRSTPRICE         VARCHAR2(4000) DEFAULT NULL,
        LASTNUMBER         VARCHAR2(4000) DEFAULT NULL,
        LASTPRICE          VARCHAR2(4000) DEFAULT NULL,
        AUTNUMBER          VARCHAR2(4000) DEFAULT NULL,
        AUTPRICE           VARCHAR2(4000) DEFAULT NULL,
        IDENT              number(17,0) DEFAULT NULL,
	    PRN                number(17,0) DEFAULT NULL
    )
